In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/GDPa1_246 IgGs_cleaned.csv")

In [3]:
df

,Unnamed: 0,antibody_id,antibody_name,Titer,Purity,SEC %Monomer,SMAC,HIC,HAC,PR_CHO,...,hc_protein_sequence,hc_dna_sequence,vl_protein_sequence,lc_protein_sequence,lc_dna_sequence,hierarchical_cluster_fold,random_fold,hierarchical_cluster_IgG_isotype_stratified_fold,light_aligned_aho,heavy_aligned_aho
0,0,GDPa1-001,abagovomab,140.25,98.530,97.010,2.730,2.590,NaN,0.337837,...,MRAWIFFLLCLAGRALAQVKLQESGAELARPGASVKLSCKASGYTF...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,DIELTQSPASLSASVGETVTITCQASENIYSYLAWHQQKQGKSPQL...,MRAWIFFLLCLAGRALADIELTQSPASLSASVGETVTITCQASENI...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,1,2,2,DIELTQSPASLSASVGETVTITCQAS--ENIY------SYLAWHQQ...,QVKLQES-GAELARPGASVKLSCKASG-YTFTN-----YWMQWVKQ...
1,1,GDPa1-002,abituzumab,193.31,99.825,97.620,2.745,2.545,3.690,0.205246,...,MRAWIFFLLCLAGRALAQVQLQQSGGELAKPGASVKVSCKASGYTF...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,DIQMTQSPSSLSASVGDRVTITCRASQDISNYLAWYQQKPGKAPKL...,MRAWIFFLLCLAGRALADIQMTQSPSSLSASVGDRVTITCRASQDI...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,1,4,0,DIQMTQSPSSLSASVGDRVTITCRAS--QDIS------NYLAWYQQ...,QVQLQQS-GGELAKPGASVKVSCKASG-YTFSS-----FWMHWVRQ...
2,2,GDPa1-003,abrezekimab,114.75,98.350,89.055,2.740,2.705,NaN,0.138773,...,MRAWIFFLLCLAGRALAQVTLKESGPVLVKPTETLTLTCTVSGFSL...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,DIQMTQSPSSLSASVGDRVTITCLASEDISNYLAWYQQKPGKAPKL...,MRAWIFFLLCLAGRALADIQMTQSPSSLSASVGDRVTITCLASEDI...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,2,2,2,DIQMTQSPSSLSASVGDRVTITCLAS--EDIS------NYLAWYQQ...,QVTLKES-GPVLVKPTETLTLTCTVSG-FSLTN-----YHVQWIRQ...
3,3,GDPa1-004,abrilumab,327.32,98.575,98.605,2.715,2.565,1.005,0.000000,...,MRAWIFFLLCLAGRALAQVQLVQSGAEVKKPGASVKVSCKVSGYTL...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,DIQMTQSPSSVSASVGDRVTITCRASQGISSWLAWYQQKPGKAPKL...,MRAWIFFLLCLAGRALADIQMTQSPSSVSASVGDRVTITCRASQGI...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,1,3,0,DIQMTQSPSSVSASVGDRVTITCRAS--QGIS------SWLAWYQQ...,QVQLVQS-GAEVKKPGASVKVSCKVSG-YTLSD-----LSIHWVRQ...
4,4,GDPa1-005,adalimumab,313.39,99.300,96.120,2.705,2.495,NaN,0.183387,...,MRAWIFFLLCLAGRALAEVQLVESGGGLVQPGRSLRLSCAASGFTF...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,DIQMTQSPSSLSASVGDRVTITCRASQGIRNYLAWYQQKPGKAPKL...,MRAWIFFLLCLAGRALADIQMTQSPSSLSASVGDRVTITCRASQGI...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,0,2,0,DIQMTQSPSSLSASVGDRVTITCRAS--QGIR------NYLAWYQQ...,EVQLVES-GGGLVQPGRSLRLSCAASG-FTFDD-----YAMHWVRQ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,241,GDPa1-242,visilizumab,303.51,94.700,98.110,2.745,2.495,4.270,0.337537,...,MRAWIFFLLCLAGRALAQVQLVQSGAEVKKPGASVKVSCKASGYTF...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,DIQMTQSPSSLSASVGDRVTITCSASSSVSYMNWYQQKPGKAPKRL...,MRAWIFFLLCLAGRALADIQMTQSPSSLSASVGDRVTITCSASSSV...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,1,1,0,DIQMTQSPSSLSASVGDRVTITCSAS--SSVS-------YMNWYQQ...,QVQLVQS-GAEVKKPGASVKVSCKASG-YTFIS-----YTMHWVRQ...
242,242,GDPa1-243,xentuzumab,281.21,98.970,99.875,10.000,4.500,NaN,0.178788,...,MRAWIFFLLCLAGRALAQVELVESGGGLVQPGGSLRLSCAASGFTF...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,DIVLTQPPSVSGAPGQRVTISCSGSSSNIGSNSVSWYQQLPGTAPK...,MRAWIFFLLCLAGRALADIVLTQPPSVSGAPGQRVTISCSGSSSNI...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,4,4,4,DIVLTQP-PSVSGAPGQRVTISCSGSS-SNIGS-----NSVSWYQQ...,QVELVES-GGGLVQPGGSLRLSCAASG-FTFTS-----YWMSWVRQ...
243,243,GDPa1-244,zalutumumab,266.55,89.430,98.065,2.705,2.590,3.760,0.000000,...,MRAWIFFLLCLAGRALAQVQLVESGGGVVQPGRSLRLSCAASGFTF...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,AIQLTQSPSSLSASVGDRVTITCRASQDISSALVWYQQKPGKAPKL...,MRAWIFFLLCLAGRALAAIQLTQSPSSLSASVGDRVTITCRASQDI...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,0,0,0,AIQLTQSPSSLSASVGDRVTITCRAS--QDIS------SALVWYQQ...,QVQLVES-GGGVVQPGRSLRLSCAASG-FTFST-----YGMHWVRQ...
244,244,GDPa1-245,zanolimumab,301.96,99.115,97.780,2.725,2.660,3.730,0.400486,...,MRAWIFFLLCLAGRALAQVQLQQWGAGLLKPSETLSLTCAVYGGSF...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,DIQMTQSPSSVSASVGDRVTITCRASQDISSWLAWYQHKPGKAPKL...,MRAWIFFLLCLAGRALADIQMTQSPSSVSASVGDRVTITCRASQDI...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,2,2,3,DIQMTQSPSSVSASVGDRVTITCRAS--QDIS------SWLAWYQH...,QVQLQQW-GAGLLKPSETLSLTCAVYG-GSFSG-----YYWSWIRQ...
245,245,GDPa1-246,zolbetuximab,375.20,100.000,99.465,2.680,2.530,NaN,0.132235,...,MRAWIFFLLCLAGRALAQVQLQQPGAELVRPGASVKLSCKASGYTF...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,DIVMTQSPSSLTVTAGEKVTMSCKSSQSLLNSGNQKNYLTWYQQKP...,MRAWIFFLLCLAGRALADIVMTQSPSSLTVTAGEKVTMSCKSSQSL...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,4,4,4,DIVMTQSPSSLTVTAGEKVTMSCKSS--QSLLNSGNQKNYLTWYQQ...,QVQLQQP-GAELVRPGASVKLSCKASG-YTFTS-----YWINWVKQ...

In [4]:
# Human-readable identifiers for each antibody candidate.
# These are kept for clarity during analysis and debugging but will NOT be used as model features.
identifier_cols = [
    "antibody_id",      # Unique internal identifier for the antibody candidate
    "antibody_name"     # Human-readable name or label for the antibody
]

# Biophysical and developability assays used as predictive features.
# These measurements describe stability, aggregation propensity, hydrophobicity,
# and polyspecificity of the antibody, which can influence expression yield (titer).
assay_cols = [
    "SMAC",             # Self-interaction measurement indicating aggregation tendency
    "HIC",              # Hydrophobic Interaction Chromatography score (hydrophobicity)
    "HAC",              # Hydrophobic interaction metric related to surface hydrophobic patches
    "PR_CHO",           # Polyspecificity reagent binding (CHO cell proteins)
    "PR_Ova",           # Polyspecificity reagent binding (ovalbumin control)
    "AC-SINS_pH6.0",    # Self-interaction assay measuring aggregation propensity at pH 6.0
    "AC-SINS_pH7.4",    # Self-interaction assay measuring aggregation propensity at physiological pH
    "Tonset",           # Temperature at which unfolding begins (thermal stability)
    "Tm1",              # First melting temperature transition (protein stability)
    "Tm2",              # Second melting temperature transition (additional stability transition)
]

# Protein sequence inputs used to generate embeddings with protein language models (PLMs).
# These represent the antibody variable regions responsible for antigen binding.
# The sequences themselves are not used directly as features but are converted into
# numerical embeddings using models such as ESM-C, ProtT5, ANKH, etc.
sequence_cols = [
    "vh_protein_sequence",  # Variable region amino acid sequence of the heavy chain
    "vl_protein_sequence",  # Variable region amino acid sequence of the light chain
]

# Categorical descriptors of the antibody chains.
# These represent antibody structural subclasses and will be encoded during modeling.
categorical_cols = [
    "hc_subtype",       # Heavy chain subtype (e.g., IgG1, IgG2)
    "lc_subtype",       # Light chain type (e.g., kappa or lambda)
]

# Target variable for prediction.
# Titer represents the expression yield of the antibody in the production system
# and is the primary developability metric we aim to predict.
target = "Titer"

In [5]:
filtered_cols = (identifier_cols + assay_cols + sequence_cols + categorical_cols + [target])

df_filtered = df[filtered_cols].copy()

In [6]:
df_filtered

,antibody_id,antibody_name,SMAC,HIC,HAC,PR_CHO,PR_Ova,AC-SINS_pH6.0,AC-SINS_pH7.4,Tonset,Tm1,Tm2,vh_protein_sequence,vl_protein_sequence,hc_subtype,lc_subtype,Titer
0,GDPa1-001,abagovomab,2.730,2.590,NaN,0.337837,0.263108,0.35,2.125,62.145,69.535,83.080,QVKLQESGAELARPGASVKLSCKASGYTFTNYWMQWVKQRPGQGLD...,DIELTQSPASLSASVGETVTITCQASENIYSYLAWHQQKQGKSPQL...,IgG1,Kappa,140.25
1,GDPa1-002,abituzumab,2.745,2.545,3.690,0.205246,0.100155,1.10,1.500,60.630,69.930,80.330,QVQLQQSGGELAKPGASVKVSCKASGYTFSSFWMHWVRQAPGQGLE...,DIQMTQSPSSLSASVGDRVTITCRASQDISNYLAWYQQKPGKAPKL...,IgG2,Kappa,193.31
2,GDPa1-003,abrezekimab,2.740,2.705,NaN,0.138773,0.101180,0.75,1.000,57.360,68.765,85.030,QVTLKESGPVLVKPTETLTLTCTVSGFSLTNYHVQWIRQPPGKALE...,DIQMTQSPSSLSASVGDRVTITCLASEDISNYLAWYQQKPGKAPKL...,IgG4,Kappa,114.75
3,GDPa1-004,abrilumab,2.715,2.565,1.005,0.000000,0.054971,0.46,-0.375,64.175,72.380,75.930,QVQLVQSGAEVKKPGASVKVSCKVSGYTLSDLSIHWVRQAPGKGLE...,DIQMTQSPSSVSASVGDRVTITCRASQGISSWLAWYQQKPGKAPKL...,IgG2,Kappa,327.32
4,GDPa1-005,adalimumab,2.705,2.495,NaN,0.183387,0.085628,0.61,7.500,62.350,72.000,84.840,EVQLVESGGGLVQPGRSLRLSCAASGFTFDDYAMHWVRQAPGKGLE...,DIQMTQSPSSLSASVGDRVTITCRASQGIRNYLAWYQQKPGKAPKL...,IgG1,Kappa,313.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,GDPa1-242,visilizumab,2.745,2.495,4.270,0.337537,0.338022,2.86,18.000,59.945,73.035,NaN,QVQLVQSGAEVKKPGASVKVSCKASGYTFISYTMHWVRQAPGQGLE...,DIQMTQSPSSLSASVGDRVTITCSASSSVSYMNWYQQKPGKAPKRL...,IgG2,Kappa,303.51
242,GDPa1-243,xentuzumab,10.000,4.500,NaN,0.178788,0.117684,25.25,26.000,NaN,NaN,NaN,QVELVESGGGLVQPGGSLRLSCAASGFTFTSYWMSWVRQAPGKGLE...,DIVLTQPPSVSGAPGQRVTISCSGSSSNIGSNSVSWYQQLPGTAPK...,IgG1,Lambda,281.21
243,GDPa1-244,zalutumumab,2.705,2.590,3.760,0.000000,0.018385,-0.14,-1.375,61.310,69.590,78.730,QVQLVESGGGVVQPGRSLRLSCAASGFTFSTYGMHWVRQAPGKGLE...,AIQLTQSPSSLSASVGDRVTITCRASQDISSALVWYQQKPGKAPKL...,IgG1,Kappa,266.55
244,GDPa1-245,zanolimumab,2.725,2.660,3.730,0.400486,0.100804,-0.14,0.625,62.860,70.485,86.180,QVQLQQWGAGLLKPSETLSLTCAVYGGSFSGYYWSWIRQPPGKGLE...,DIQMTQSPSSVSASVGDRVTITCRASQDISSWLAWYQHKPGKAPKL...,IgG1,Kappa,301.96
245,GDPa1-246,zolbetuximab,2.680,2.530,NaN,0.132235,0.101020,30.60,29.500,59.875,69.955,84.895,QVQLQQPGAELVRPGASVKLSCKASGYTFTSYWINWVKQRPGQGLE...,DIVMTQSPSSLTVTAGEKVTMSCKSSQSLLNSGNQKNYLTWYQQKP...,IgG1,Kappa,375.20