In [1]:
import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from matplotlib.gridspec import GridSpec
import seaborn as sns
from scipy.stats import mannwhitneyu

In [8]:
# Set to None to display all columns
pd.set_option('display.max_columns', None)

# To also display all rows if needed
pd.set_option('display.max_rows', None)

'''

=======================================================
SUMMARY: Consistently Wrong Antibodies
=======================================================
  antibody_name  Titer  n_models_high_err  mean_abserr   HIC   HAC  SEC %Monomer  AC-SINS_pH6.0 hc_subtype lc_subtype
   emibetuzumab 781.93                  5   509.639297 2.785   NaN        91.580          12.25       IgG4      Kappa
     inotuzumab 637.93                  5   400.418494 2.760 4.785        85.305           2.85       IgG4      Kappa
    eptinezumab 642.34                  5   360.173411 3.680   NaN        99.675          -0.14       IgG1      Kappa
      orticumab 700.57                  5   356.455963 2.520   NaN        99.795           2.60       IgG2     Lambda
    figitumumab 571.63                  5   352.723352 2.990   NaN        99.520          13.96       IgG2      Kappa
    lexatumumab  52.18                  5   321.476039 2.500   NaN        96.440           0.75       IgG1     Lambda
     olokizumab 516.74                  5   277.155538 2.840   NaN        91.080           1.35       IgG4      Kappa
    dalotuzumab 464.78                  5   271.620236 2.730   NaN        98.360           0.60       IgG1      Kappa
    epratuzumab 491.08                  5   260.903758 2.545 4.010        97.045           0.86       IgG1      Kappa
    mitazalimab 678.57                  5   259.348941 2.735 4.110        98.340          23.35       IgG1     Lambda
      tovetumab 491.52                  5   239.305996 2.500 3.880        87.910           0.61       IgG2      Kappa
    dacetuzumab  34.26                  5   227.059717 2.480   NaN        92.020           0.25       IgG1      Kappa
   farletuzumab 464.78                  5   217.756912 2.660 3.650        98.175           0.10       IgG1      Kappa
      oleclumab 591.12                  5   202.308685 2.955 4.210        98.590           3.85       IgG1     Lambda
     cemiplimab  72.14                  5   200.551201 2.730   NaN        84.655           1.86       IgG4      Kappa
  cabiralizumab  57.13                  5   183.182051 2.720   NaN        87.140           0.35       IgG4      Kappa
      icrucumab  46.59                  5   178.874155 3.280   NaN        95.980           0.75       IgG1      Kappa
    ublituximab  46.59                  5   178.385910 3.140   NaN        95.020           0.75       IgG1      Kappa
     utomilumab 438.38                  5   175.676721 3.035   NaN        99.845          16.11       IgG2     Lambda
   lebrikizumab  57.13                  5   172.619080 3.485   NaN        89.835           0.85       IgG4      Kappa
    motavizumab 383.43                  5   168.880717 2.695   NaN        97.825           0.35       IgG1      Kappa
    nimotuzumab  60.31                  5   165.564249 2.730   NaN        94.940           0.00       IgG1      Kappa
      galiximab 179.14                  5   163.836364 3.400   NaN        98.410          -0.04       IgG1     Lambda
     cetrelimab  69.28                  5   163.810662 3.400   NaN        95.640          15.75       IgG4      Kappa
      sirukumab  83.88                  5   163.497677 3.180   NaN        99.040          17.86       IgG1      Kappa
     emapalumab 202.74                  5   162.895814 2.795 1.810        94.630           0.61       IgG1     Lambda
     patritumab  66.54                  5   161.802758 2.845   NaN        94.480           1.36       IgG1      Kappa
   zolbetuximab 375.20                  5   161.309254 2.530   NaN        99.465          30.60       IgG1      Kappa
    ocrelizumab 420.17                  5   160.769076 2.860   NaN        99.615           1.61       IgG1      Kappa
    romosozumab 393.92                  5   160.428236 2.565   NaN        98.360           0.35       IgG2      Kappa
   otlertuzumab  66.54                  5   160.053292 3.080   NaN        93.990           0.25       IgG1      Kappa
    palivizumab 367.30                  5   156.258284 2.570 4.040        97.840          -0.25       IgG1      Kappa
    fezakinumab 251.19                  5   152.096022 3.305   NaN        96.035           0.36       IgG1     Lambda
    tigatuzumab 121.41                  5   145.300499 2.885   NaN        98.930           1.86       IgG1      Kappa
rozanolixizumab 125.49                  5   141.801515 2.575   NaN        87.580           0.86       IgG4      Kappa
    onartuzumab 375.20                  5   140.113463 2.760   NaN        93.020          -0.39       IgG1      Kappa
      fasinumab  88.48                  5   136.748164 2.770 1.505        88.340           0.86       IgG4      Kappa
     alirocumab  89.39                  5   136.007169 2.535   NaN        96.720          -0.14       IgG1      Kappa

=======================================================
GROUP MEDIANS (numeric assay readouts)
=======================================================
                     Titer   HIC   HAC  SEC %Monomer  AC-SINS_pH6.0  Tonset    Tm1    Tm2  mean_abserr
failure_group                                                                                         
consistently_wrong  309.24  2.76  4.01         96.24           0.80   60.48  70.38  81.68       174.15
sometimes_wrong     177.67  2.79  3.90         97.25           0.86   60.82  70.53  83.08       109.68
consistently_right  228.75  2.72  3.75         97.62           0.75   60.89  70.57  82.84        46.25




'''

In [2]:
df = pd.read_csv(r"/home/allen/mads_UMICH/capstone699_repo/data/modeling/failure_eda/cdr_feature_group_stats_246.csv")

In [4]:
dfr = pd.read_csv(r"/home/allen/mads_UMICH/capstone699_repo/data/modeling/failure_eda/gdpa1_with_failure_flags_246.csv")

In [12]:
df.head(63)

,feature,col,p_value,median_diff_wrong_minus_right,median_wrong,median_right
0,cdrL3_len,cdrL3_len_CDR_feature,0.019127,0.000000,9.000000,9.000000
1,cdrL1_charge,cdrL1_charge_CDR_feature,0.022138,0.000000,0.000000,0.000000
2,cdrH1_hyd_frac,cdrH1_hyd_frac_CDR_feature,0.049863,0.090909,0.454545,0.363636
3,cdrL2_oxidn,cdrL2_oxidn_CDR_feature,0.058030,0.000000,0.000000,0.000000
4,cdrL3_isom,cdrL3_isom_CDR_feature,0.111217,0.000000,0.000000,0.000000
5,cdrH3_gravy,cdrH3_gravy_CDR_feature,0.113652,0.167112,-0.555965,-0.723077
6,cdrL3_deamid,cdrL3_deamid_CDR_feature,0.113816,0.000000,0.000000,0.000000
7,cdrL1_len,cdrL1_len_CDR_feature,0.131692,1.500000,10.500000,9.000000
8,cdrL3_charge,cdrL3_charge_CDR_feature,0.132253,0.000000,0.000000,0.000000
9,VL_unpaired_cys,VL_unpaired_cys_CDR_feature,0.136528,0.000000,0.000000,0.000000
10,VH_gravy,VH_gravy_CDR_feature,0.145165,0.044020,-0.263333,-0.307353
11,cdrL1_gravy,cdrL1_gravy_CDR_feature,0.164965,-0.178772,-0.497576,-0.318803
12,VL_isom_total,VL_isom_total_CDR_feature,0.189869,0.000000,0.000000,0.000000
13,cdrH1_gravy,cdrH1_gravy_CDR_feature,0.208270,0.085985,-0.195833,-0.281818
14,VL_deamid_total,VL_deamid_total_CDR_feature,0.212058,0.000000,0.000000,0.000000
15,cdrH2_charge,cdrH2_charge_CDR_feature,0.215665,0.000000,0.000000,0.000000
16,VL_hyd_frac,VL_hyd_frac_CDR_feature,0.238724,-0.006172,0.339623,0.345794
17,cdrH2_hyd_frac,cdrH2_hyd_frac_CDR_feature,0.291620,-0.020027,0.294118,0.314145
18,cdrL3_hyd_frac,cdrL3_hyd_frac_CDR_feature,0.298933,0.003846,0.320513,0.316667
19,cdrL1_hyd_frac,cdrL1_hyd_frac_CDR_feature,0.306326,-0.014610,0.360390,0.375000
20,VL_oxidn_total,VL_oxidn_total_CDR_feature,0.320837,1.000000,3.000000,2.000000
21,VH_charge,VH_charge_CDR_feature,0.390059,0.000000,1.000000,1.000000
22,cdrH3_oxidn,cdrH3_oxidn_CDR_feature,0.394779,0.000000,1.000000,1.000000
23,cdrL2_hyd_frac,cdrL2_hyd_frac_CDR_feature,0.398156,0.000000,0.375000,0.375000
24,Unnamed: 0,Unnamed: 0_CDR_feature,0.449682,12.500000,131.000000,118.500000
25,total_oxidn,total_oxidn_CDR_feature,0.463605,0.000000,9.000000,9.000000
26,total_deamid,total_deamid_CDR_feature,0.464095,1.000000,2.000000,1.000000
27,cdrL3_gravy,cdrL3_gravy_CDR_feature,0.480246,0.077273,-1.072727,-1.150000
28,cdrH1_isom,cdrH1_isom_CDR_feature,0.481230,0.000000,0.000000,0.000000
29,cdrH1_len,cdrH1_len_CDR_feature,0.534128,0.000000,11.000000,11.000000
30,VL_gravy,VL_gravy_CDR_feature,0.549116,-0.008328,-0.337416,-0.329088
31,cdrH2_gravy,cdrH2_gravy_CDR_feature,0.573860,-0.097794,-0.976471,-0.878676
32,cdrH3_isom,cdrH3_isom_CDR_feature,0.574649,0.000000,0.000000,0.000000
33,cdrL2_deamid,cdrL2_deamid_CDR_feature,0.579132,0.000000,0.000000,0.000000
34,cdrL3_oxidn,cdrL3_oxidn_CDR_feature,0.598153,0.000000,0.000000,0.000000
35,cdrH3_hyd_frac,cdrH3_hyd_frac_CDR_feature,0.601033,0.000000,0.500000,0.500000
36,VH_oxidn_total,VH_oxidn_total_CDR_feature,0.601675,0.000000,6.000000,6.000000
37,cdrH3_len,cdrH3_len_CDR_feature,0.619268,0.000000,12.000000,12.000000
38,VH_unpaired_cys,VH_unpaired_cys_CDR_feature,0.624079,0.000000,0.000000,0.000000
39,VL_glycan_total,VL_glycan_total_CDR_feature,0.624079,0.000000,0.000000,0.000000
40,cdrL2_charge,cdrL2_charge_CDR_feature,0.630979,0.000000,0.000000,0.000000
41,cdrH2_deamid,cdrH2_deamid_CDR_feature,0.666023,0.000000,0.000000,0.000000
42,cdrH3_charge,cdrH3_charge_CDR_feature,0.667504,0.000000,0.000000,0.000000
43,cdrH3_aromatic_frac,cdrH3_aromatic_frac_CDR_feature,0.673758,0.000000,0.250000,0.250000
44,VH_isom_total,VH_isom_total_CDR_feature,0.675056,0.000000,1.000000,1.000000
45,VH_deamid_total,VH_deamid_total_CDR_feature,0.696800,0.000000,1.000000,1.000000
46,cdrH2_len,cdrH2_len_CDR_feature,0.713263,0.000000,17.000000,17.000000
47,cdrL2_isom,cdrL2_isom_CDR_feature,0.734692,0.000000,0.000000,0.000000
48,cdrH3_deamid,cdrH3_deamid_CDR_feature,0.734692,0.000000,0.000000,0.000000
49,cdrL2_gravy,cdrL2_gravy_CDR_feature,0.762428,0.025000,-0.675000,-0.700000
50,cdrH1_oxidn,cdrH1_oxidn_CDR_feature,0.787511,0.000000,1.000000,1.000000
51,cdrH1_deamid,cdrH1_deamid_CDR_feature,0.830730,0.000000,0.000000,0.000000
52,VH_hyd_frac,VH_hyd_frac_CDR_feature,0.858259,0.001496,0.393162,0.391667
53,cdrL1_deamid,cdrL1_deamid_CDR_feature,0.864629,0.000000,0.000000,0.000000
54,cdrL1_isom,cdrL1_isom_CDR_feature,0.865711,0.000000,0.000000,0.000000
55,VH_glycan_total,VH_glycan_total_CDR_feature,0.866347,0.000000,0.000000,0.000000
56,cdrH2_isom,cdrH2_isom_CDR_feature,0.868009,0.000000,0.000000,0.000000
57,cdrL1_oxidn,cdrL1_oxidn_CDR_feature,0.877226,0.000000,0.000000,0.000000
58,VL_charge,VL_charge_CDR_feature,0.902891,0.000000,1.000000,1.000000
59,cdrH1_charge,cdrH1_charge_CDR_feature,0.939036,0.000000,0.000000,0.000000
60,cdrH2_oxidn,cdrH2_oxidn_CDR_feature,0.995018,0.000000,0.000000,0.000000
61,cdrL2_len,cdrL2_len_CDR_feature,1.000000,0.000000,8.000000,8.000000
62,cdrH3_glycan_sequon,cdrH3_glycan_sequon_CDR_feature,1.000000,0.000000,0.000000,0.000000

In [11]:
dfr.head()

,Unnamed: 0,antibody_id,antibody_name,Titer,Purity,SEC %Monomer,SMAC,HIC,HAC,PR_CHO,PR_Ova,AC-SINS_pH6.0,AC-SINS_pH7.4,Tonset,Tm1,Tm2,hc_subtype,lc_subtype,highest_clinical_trial_asof_feb2025,est_status_asof_feb2025,vh_protein_sequence,hc_protein_sequence,hc_dna_sequence,vl_protein_sequence,lc_protein_sequence,lc_dna_sequence,hierarchical_cluster_fold,random_fold,hierarchical_cluster_IgG_isotype_stratified_fold,light_aligned_aho,heavy_aligned_aho,n_models_high_err,failure_group,mean_abserr,std_abserr,prot_t5_model_abserr,esmc_model_abserr,protbert_model_abserr,ankh_model_abserr,prost_t5_model_abserr,prot_t5_model_pred,esmc_model_pred,protbert_model_pred,ankh_model_pred,prost_t5_model_pred,prot_t5_model_high_err,esmc_model_high_err,protbert_model_high_err,ankh_model_high_err,prost_t5_model_high_err,Unnamed: 0_CDR_feature,cdrH1_len_CDR_feature,cdrH1_gravy_CDR_feature,cdrH1_hyd_frac_CDR_feature,cdrH1_charge_CDR_feature,cdrH1_deamid_CDR_feature,cdrH1_isom_CDR_feature,cdrH1_oxidn_CDR_feature,cdrH2_len_CDR_feature,cdrH2_gravy_CDR_feature,cdrH2_hyd_frac_CDR_feature,cdrH2_charge_CDR_feature,cdrH2_deamid_CDR_feature,cdrH2_isom_CDR_feature,cdrH2_oxidn_CDR_feature,cdrH3_len_CDR_feature,cdrH3_gravy_CDR_feature,cdrH3_hyd_frac_CDR_feature,cdrH3_charge_CDR_feature,cdrH3_deamid_CDR_feature,cdrH3_isom_CDR_feature,cdrH3_oxidn_CDR_feature,cdrL1_len_CDR_feature,cdrL1_gravy_CDR_feature,cdrL1_hyd_frac_CDR_feature,cdrL1_charge_CDR_feature,cdrL1_deamid_CDR_feature,cdrL1_isom_CDR_feature,cdrL1_oxidn_CDR_feature,cdrL2_len_CDR_feature,cdrL2_gravy_CDR_feature,cdrL2_hyd_frac_CDR_feature,cdrL2_charge_CDR_feature,cdrL2_deamid_CDR_feature,cdrL2_isom_CDR_feature,cdrL2_oxidn_CDR_feature,cdrL3_len_CDR_feature,cdrL3_gravy_CDR_feature,cdrL3_hyd_frac_CDR_feature,cdrL3_charge_CDR_feature,cdrL3_deamid_CDR_feature,cdrL3_isom_CDR_feature,cdrL3_oxidn_CDR_feature,cdrH3_aromatic_frac_CDR_feature,cdrH3_glycan_sequon_CDR_feature,VH_deamid_total_CDR_feature,VH_isom_total_CDR_feature,VH_oxidn_total_CDR_feature,VH_glycan_total_CDR_feature,VH_hyd_frac_CDR_feature,VH_gravy_CDR_feature,VH_charge_CDR_feature,VL_deamid_total_CDR_feature,VL_isom_total_CDR_feature,VL_oxidn_total_CDR_feature,VL_glycan_total_CDR_feature,VL_hyd_frac_CDR_feature,VL_gravy_CDR_feature,VL_charge_CDR_feature,total_deamid_CDR_feature,total_oxidn_CDR_feature,VH_unpaired_cys_CDR_feature,VL_unpaired_cys_CDR_feature
0,0,GDPa1-001,abagovomab,140.25,98.530,97.010,2.730,2.590,NaN,0.337837,0.263108,0.35,2.125,62.145,69.535,83.08,IgG1,Kappa,Phase-III,Discontinued,QVKLQESGAELARPGASVKLSCKASGYTFTNYWMQWVKQRPGQGLD...,MRAWIFFLLCLAGRALAQVKLQESGAELARPGASVKLSCKASGYTF...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,DIELTQSPASLSASVGETVTITCQASENIYSYLAWHQQKQGKSPQL...,MRAWIFFLLCLAGRALADIELTQSPASLSASVGETVTITCQASENI...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,1,2,2,DIELTQSPASLSASVGETVTITCQAS--ENIY------SYLAWHQQ...,QVKLQES-GAELARPGASVKLSCKASG-YTFTN-----YWMQWVKQ...,1.0,sometimes_wrong,88.108057,40.272516,86.800857,56.775752,63.338113,76.547366,157.078199,227.050857,197.025752,203.588113,216.797366,297.328199,0.0,0.0,0.0,0.0,1.0,0,11,-0.763636,0.454545,0,0,0,2,17,-1.188235,0.294118,2,0,1,0,12,-0.633333,0.583333,0,0,0,1,9,-0.122222,0.555556,-1,0,0,0,8,-0.3000,0.500,1,1,0,0,9,-0.622222,0.333333,0,0,0,0,0.333333,0,0,2,7,0,0.386555,-0.502521,4,1,0,1,0,0.355140,-0.257009,1,1,8,0,0
1,1,GDPa1-002,abituzumab,193.31,99.825,97.620,2.745,2.545,3.690,0.205246,0.100155,1.10,1.500,60.630,69.930,80.33,IgG2,Kappa,Phase-II,Active,QVQLQQSGGELAKPGASVKVSCKASGYTFSSFWMHWVRQAPGQGLE...,MRAWIFFLLCLAGRALAQVQLQQSGGELAKPGASVKVSCKASGYTF...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,DIQMTQSPSSLSASVGDRVTITCRASQDISNYLAWYQQKPGKAPKL...,MRAWIFFLLCLAGRALADIQMTQSPSSLSASVGDRVTITCRASQDI...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,1,4,0,DIQMTQSPSSLSASVGDRVTITCRAS--QDIS------NYLAWYQQ...,QVQLQQS-GGELAKPGASVKVSCKASG-YTFSS-----FWMHWVRQ...,0.0,consistently_right,32.191600,7.806558,33.826759,41.179832,37.205735,21.833185,26.912492,227.136759,234.489832,230.515735,215.143185,220.222492,0.0,0.0,0.0,0.0,0.0,1,11,-0.127273,0.454545,0,0,0,2,17,-1.300000,0.352941,-1,0,0,0,11,0.109091,0.545455,0,0,0,1,9,-0.366667,0.444444,-1,0,0,0,8,-0.9375,0.375,1,0,0,0,9,-1.377778,0.222222,0,0,0,0,0.181818,0,0,0,8,0,0.381356,-0.390678,-1,0,0,2,0,0.336449,-0.452336,2,0,10,0,0
2,2,GDPa1-003,abrezekimab,114.75,98.350,89.055,2.740,2.705,NaN,0.138773,0.101180,0.75,1.000,57.360,68.765,85.03,IgG4,Kappa,Phase-I,Discontinued,QVTLKESGPVLVKPTETLTLTCTVSGFSLTNYHVQWIRQPPGKALE...,MRAWIFFLLCLAGRALAQVTLKESGPVLVKPTETLTLTCTVSGFSL...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,DIQMTQSPSSLSASVGDRVTITCLASEDISNYLAWYQQKPGKAPKL...,MRAWIFFLLCLAGRALADIQMTQSPSSLSASVGDRVTITCLASEDI...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,2,2,2,DIQMTQSPSSLSASVGDRVTITCLAS--EDIS------NYLAWYQQ...,QVTLKES-GPVLVKPTETLTLTCTVSG-FSLTN-----YHVQWIRQ...,2.0,sometimes_wrong,107.968553,28.555808,87.191652,142.516506,134.500328,95.576067,80.058212,201.941652,257.266506,249.250328,210.326067,194.808212,0.0,1.0,1.0,0.0,0.0,2,11,-0.309091,0.363636,0,0,0,0,16,-0.168750,0.375000,-1,1,1,2,14,-0.292857,0.571429,-2,0,1,1,9,-0.366667,0.444444,-2,0,0,0,8,-1.7125,0.250,0,0,0,0,9,-0.988889,0.333333,1,0,0,0,0.214286,0,1,2,8,0,0.391667,-0.119167,-2,0,1,2,0,0.345794,-0.339252,0,1,10,0,0
3,3,GDPa1-004,abrilumab,327.32,98.575,98.605,2.715,2.565,1.005,0.000000,0.054971,0.46,-0.375,64.175,72.380,75.93,IgG2,Kappa,Phase-II,Discontinued,QVQLVQSGAEVKKPGASVKVSCKVSGYTLSDLSIHWVRQAPGKGLE...,MRAWIFFLLCLAGRALAQVQLVQSGAEVKKPGASVKVSCKVSGYTL...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,DIQMTQSPSSVSASVGDRVTITCRASQGISSWLAWYQQKPGKAPKL...,MRAWIFFLLCLAGRALADIQMTQSPSSVSASVGDRVTITCRASQGI...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,1,3,0,DIQMTQSPSSVSASVGDRVTITCRAS--QGIS------SWLAWYQQ...,QVQLVQS-GAEVKKPGASVKVSCKVSG-YTLSD-----LSIHWVRQ...,0.0,consistently_right,80.959809,8.382663,76.882580,91.433600,72.364399,88.322360,75.796107,250.437420,235.886400,254.955601,238.997640,251.523893,0.0,0.0,0.0,0.0,0.0,3,11,0.054545,0.363636,-1,0,0,0,17,-1.047059,0.294118,-2,0,1,0,11,-0.518182,0.272727,-1,0,0,1,9,0.322222,0.444444,0,0,0,1,8,-0.5875,0.375,-1,0,0,0,9,-1.100000,0.333333,0,1,0,1,0.181818,0,0,1,7,0,0.355932,-0.350000,-4,1,0,4,0,0.345794,-0.335514,1,1,11,0,0
4,4,GDPa1-005,adalimumab,313.39,99.300,96.120,2.705,2.495,NaN,0.183387,0.085628,0.61,7.500,62.350,72.000,84.84,IgG1,Kappa,Approved,Active,EVQLVESGGGLVQPGRSLRLSCAASGFTFDDYAMHWVRQAPGKGLE...,MRAWIFFLLCLAGRALAEVQLVESGGGLVQPGRSLRLSCAASGFTF...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,DIQMTQSPSSLSASVGDRVTITCRASQGIRNYLAWYQQKPGKAPKL...,MRAWIFFLLCLAGRALADIQMTQSPSSLSASVGDRVTITCRASQGI...,GCCGCCACCATGAGAGCCTGGATCTTTTTCCTGCTGTGCCTGGCTG...,0,2,0,DIQMTQSPSSLSASVGDRVTITCRAS--QGIR------NYLAWYQQ...,EVQLVES-GGGLVQPGRSLRLSCAASG-FTFDD-----YAMHWVRQ...,0.0,consistently_right,48.801602,9.105934,59.409807,54.046387,39.692285,38.875678,51.983853,253.980193,259.343613,273.697715,274.514322,261.406147,0.0,0.0,0.0,0.0,0.0,4,11,-0.372727,0.454545,-2,0,0,1,17,-0.335294,0.411765,-3,1,1,1,14,0.107143,0.500000,0,0,0,0,9,-0.433333,0.444444,1,0,0,0,8,0.0375,0.500,0,0,0,0,9,-2.122222,0.333333,2,0,0,0,0.142857,0,4,1,6,0,0.421488,-0.184298,-3,0,0,2,0,0.355140,-0.402804,5,4,8,0,0

In [6]:
df.shape

(63, 6)

In [7]:
dfr.shape

(246, 113)